# Generated by Django 4.0.3 on 2022-04-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_remove_records_doctor_delete_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='businessName',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
